[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "link-args=-o out.js",
    "-C",
    "link-args=-s EXPORTED_FUNCTIONS=['_eval_ruby_script_int','_main']",
    "-C",
    "link-args=-s EXPORTED_RUNTIME_METHODS=['ccall','cwrap']",
    "-C",
    "link-args=-s MODULARIZE=0",
    "-C",
    "link-args=-s SINGLE_FILE=1",
    "-C",
    "link-args=-s ALLOW_MEMORY_GROWTH=1",
    "-C",
    "link-args=-s INITIAL_MEMORY=16777216",
    "-C",
    "link-args=-s FILESYSTEM=0",
    "-C",
    "link-args=-s ASSERTIONS=0",
    "-C",
    "link-args=-flto",
    "-C",
    "link-args=-Oz",
    "-C",
    "link-args=-s SUPPORT_LONGJMP=emscripten",
    "-C",
    "link-args=-s SINGLE_FILE_BINARY_ENCODE=0",
    "-C",
    "link-args=-s LEGACY_VM_SUPPORT=1",
    "-Z",
    "emscripten-wasm-eh=false",
]
[target.wasm32-unknown-unknown]
